### PR TITLE
7.2.x

### PR DESCRIPTION
**Pull request by Mihai-B**

### CODE REVIEW

**Comment by Mihai-B** [comment]
@alejandroSuch I think you have to create a branch 7.2.x and change the branch to it

**Comment by Mihai-B** [comment]
Let me know how we can merge this because I need to merge the 7.2.x-chromium as well

**Comment by alejandroSuch** [comment]
Hello @Mihai-B!

I've created branches `7.2.x` and `7.2.x-chromium`.

I think we could make some brainstorming to get an easier way to maintain this repo. What do you think?

Regards,
Alex

**Comment by Mihai-B** [comment]
I agree. I will look for some guidelines on how it is best to set up the project on github.

**Comment by Mihai-B** [comment]
Also, I forgot to mention, for each version that we do push to docker hub, a tag in git should appear with that version.
So for example I want to add the new angular-cli:7.3.0

- I update in folder 7.x the cli version to the desired one(angular-cli:7.3.0).
- Commit
- build docker image
- push docker image to docker hub
- set a tag on the newly created commit with the message: 7.3.0
- push to github
- create pull request on alejandroSuch/angular-cli with the new commits

**Comment by alejandroSuch** [comment]
> Maybe instead of using branches, we should have in the repository just the master branch and folders for each version. so 6.x has a folder with the script to create docker images with angular cli-6 and another folder for 7.x where you can build the images for angular cli 7.0.x. And a general readme that we document with all the current versions that are on the docker hub.
> 
> What do you think ?

So the build & push to dockerhub would be in a local computer? Nowadays, it is built automatically if a push is done in the branch.

Ok, I'll study how to keep on making automatic builds

**Comment by Mihai-B** [comment]
> > Maybe instead of using branches, we should have in the repository just the master branch and folders for each version. so 6.x has a folder with the script to create docker images with angular cli-6 and another folder for 7.x where you can build the images for angular cli 7.0.x. And a general readme that we document with all the current versions that are on the docker hub.
> > What do you think ?
> 
> So the build & push to dockerhub would be in a local computer? Nowadays, it is built automatically if a push is done in the branch.
> 
> Ok, I'll study how to keep on making automatic builds

I did not think about autobuild process. Maybe it is better with autobuild. I will try some stuff and get back to it then...

**Comment by alejandroSuch** [comment]
> > > Maybe instead of using branches, we should have in the repository just the master branch and folders for each version. so 6.x has a folder with the script to create docker images with angular cli-6 and another folder for 7.x where you can build the images for angular cli 7.0.x. And a general readme that we document with all the current versions that are on the docker hub.
> > > What do you think ?
> > 
> > 
> > So the build & push to dockerhub would be in a local computer? Nowadays, it is built automatically if a push is done in the branch.
> > Ok, I'll study how to keep on making automatic builds
> 
> I did not think about autobuild process. Maybe it is better with autobuild. I will try some stuff and get back to it then...

Give me your dockerhub user so i can give you permissions

**Comment by Mihai-B** [comment]
My user is [rat2000](https://cloud.docker.com/u/rat2000), but I think I allready have permissions

**Pull request closed without merging**
