### PR TITLE
Changed mount point in examples to /app (/opt being already used by yarn)

### PR DESCRIPTION
**Pull request by nlko**
I think yarn installation is missing

### CODE REVIEW

**Comment by alejandroSuch** [comment]
Hi @nlko! Thanks for your collaboration. Yarn is already included on `node:6-alpine` image.

You can test it this way:

```
$ docker run -it --rm node:6-alpine yarn --version
0.23.2
```

If it's ok for you, I'll close this PR.

Regards,
Alex

**Comment by nlko** [comment]
Hi Alex,

Ok I think I find the problem.

You're right about yarn in node alpine.
```
$ docker run -it --rm node:6-alpine yarn --version
0.24.6
```
If I follow the readme example that tries to mount /opt it makes yarn "being" uninstalled 

```
$ docker run -it --rm -w /opt -v $(pwd):/opt alexsuch/angular-cli yarn --version
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"yarn\": executable file not found in $PATH".
ERRO[0000] error getting events from daemon: context canceled 
```

But with the same command using another mount point it works
```
$ docker run -it --rm -w /tmp -v $(pwd):/tmp alexsuch/angular-cli yarn --version
0.24.6
```

As you can see there is a yarn folder in /opt

```
$ docker run -it --rm alexsuch/angular-cli ls -la /opt/yarn
total 24
drwxr-xr-x    4 root     root          4096 Jun  8 16:44 .
drwxr-xr-x    3 root     root          4096 Jun  8 16:44 ..
-rw-r--r--    1 node     node          1346 May 23 20:05 LICENSE
drwxr-xr-x    2 node     node          4096 May 23 20:05 bin
drwxr-xr-x    2 node     node          4096 May 23 20:05 lib
-rw-r--r--    1 node     node          3450 May 23 20:05 package.json

```

Regards,

Nicolas

**Comment by alejandroSuch** [comment]
You're right! Thanks! Do you want to make a PR with an updated version of the readme file?

**Comment by nlko** [comment]
Hi Alejandro, I updated the README (and canceled any modification I made in the Dockerfile)

**Pull request merged**
